apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-kraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-kraft
  template:
    metadata:
      labels:
        app: kafka-kraft
    spec:
      containers:
        - name: kafka-kraft
          image: apache/kafka:3.9.0
          ports:
            - containerPort: 9092
              name: kafka-port
            - containerPort: 29092
              name: broker-port
            - containerPort: 29093
              name: ctrl-port
          env:
            - name: KAFKA_NODE_ID
              value: "1"
            - name: CLUSTER_ID
              value: "cluster-12345"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-kraft.default.svc.cluster.local:29092,PLAINTEXT_HOST://kafka-kraft.default.svc.cluster.local:9092"
            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@:29093"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:29092,CONTROLLER://:29093,PLAINTEXT_HOST://:9092"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
          volumeMounts:
            - name: temperature-load-script
              mountPath: /app/
      volumes:
        - name: temperature-load-script
          hostPath:
            path: /kafka-streams-quarkus-vs-spring/
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-kraft
spec:
  ports:
    - name: kafka-port
      port: 9092
      targetPort: 9092
    - name: broker-port
      port: 29092
      targetPort: 29092
    - name: ctrl-port
      port: 29093
      targetPort: 29093
  selector:
    app: kafka-kraft
