apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  custom-prometheus.yml: |
    global:
      scrape_interval: 5s 
      evaluation_interval: 5s 
    scrape_configs:
      - job_name: 'quarkus-iot-stateless'
        static_configs:
          - targets: ['quarkus-iot-stateless.default.svc.cluster.local:9404']
      - job_name: 'quarkus-iot-stateful'
        static_configs:
          - targets: ['quarkus-iot-stateful.default.svc.cluster.local:9404']
      - job_name: 'springboot-iot-stateless'
        static_configs:
          - targets: ['springboot-iot-stateless.default.svc.cluster.local:9404']
      - job_name: 'springboot-iot-stateful'
        static_configs:
          - targets: ['springboot-iot-stateful.default.svc.cluster.local:9404']

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v3.1.0
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
          args:
            - '--config.file=/etc/prometheus/custom-prometheus.yml'
      volumes:
        - name: prometheus-config-volume
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9090
      nodePort: 30091
